print('Olá, mundo')
print('Me chamo Bárbara')
print('Trabalho em um escritório de advocacia')
print('Faço faculdade de Ciências Contabéis')
print('Tenho apenas 18 anos')
print('Finalizei o meu prmeiro ano da faculdade')
print('Gosto da cor preta')
print('Sou pisciana')
print('Hoje eu dormi no onibus e passei o ponto de descer')
print('Estou com muita fome')
